# Site settings
title: Arnaud Besnier
email: arnaudibesnier@gmail.com
description: >
  If you want to know more about me, this is the right spot.
  Explore my world and contact me if you need.
baseurl: ""
url: "http://arnaudbesnier.com"
twitter_username: arnaud_besnier
github_username: arnaudbesnier

# Build settings
markdown: kramdown
